### ISSUE TITLE
Building against OpenSSL-enabled liboqs fails

### ISSUE THREAD

**Issue by dmjones** [thales-e-security/goliboqs#2]
If liboqs is built with OpenSSL support (e.g. `./configure --enable-openssl`), it won't work with this wrapper.

I'm assuming we need additional `LDFLAG` entries. This can be done without touching the source code, via the `CGO_LDFLAGS` environment variable. However, I've failed thus far to get that working.

I've tried:

```
CGO_LDFLAGS="-L/usr/lib/x86_64-linux-gnu/ -lcrypto" go test .
CGO_LDFLAGS="-L/usr/lib/ -lcrypto" go test .
```

to no avail. The error is usually `undefined symbol: BN_CTX_get`. (I modify the source to print `dlerror()`). This symbol is indeed defined in libcrypto:

```
$ nm --dynamic /usr/lib/x86_64-linux-gnu/libcrypto.so | grep BN_CTX_get
00000000000a5830 T BN_CTX_get
```

**Comment by dmjones** [comment]
This is a linking oversight in liboqs, see https://github.com/open-quantum-safe/liboqs/issues/485.

In the interim, the following *additional* LDFLAGS flags are needed to work with an OpenSSL build of liboqs: `-Wl,--no-as-needed -lcrypto`.

For instance:

```
CGO_LDFLAGS="-Wl,--no-as-needed -lcrypto" go test -v
```

**Comment by dstebila** [comment]
open-quantum-safe/liboqs#485 now resolved.
